// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { AiHealthApiV1AiHealthGetData, AiHealthApiV1AiHealthGetResponses, ChatApiV1AiChatPostData, ChatApiV1AiChatPostErrors, ChatApiV1AiChatPostResponses, ChatStreamApiV1AiChatStreamPostData, ChatStreamApiV1AiChatStreamPostErrors, ChatStreamApiV1AiChatStreamPostResponses, CreateItemApiV1ItemsPostData, CreateItemApiV1ItemsPostErrors, CreateItemApiV1ItemsPostResponses, DeleteItemApiV1ItemsItemIdDeleteData, DeleteItemApiV1ItemsItemIdDeleteErrors, DeleteItemApiV1ItemsItemIdDeleteResponses, GetItemApiV1ItemsItemIdGetData, GetItemApiV1ItemsItemIdGetErrors, GetItemApiV1ItemsItemIdGetResponses, GetMyProfileApiV1UsersMeGetData, GetMyProfileApiV1UsersMeGetResponses, GetTracesApiV1AiTracesGetData, GetTracesApiV1AiTracesGetResponses, HealthCheckApiV1HealthGetData, HealthCheckApiV1HealthGetResponses, ListItemsApiV1ItemsGetData, ListItemsApiV1ItemsGetErrors, ListItemsApiV1ItemsGetResponses, LoginApiV1AuthLoginPostData, LoginApiV1AuthLoginPostErrors, LoginApiV1AuthLoginPostResponses, RunBackgroundTaskApiV1TasksRunPostData, RunBackgroundTaskApiV1TasksRunPostResponses, UpdateItemApiV1ItemsItemIdPatchData, UpdateItemApiV1ItemsItemIdPatchErrors, UpdateItemApiV1ItemsItemIdPatchResponses, UpdateMyProfileApiV1UsersMePatchData, UpdateMyProfileApiV1UsersMePatchErrors, UpdateMyProfileApiV1UsersMePatchResponses, UploadFileApiV1UploadPostData, UploadFileApiV1UploadPostErrors, UploadFileApiV1UploadPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health Check
 *
 * Health check endpoint for Docker/Dokploy.
 * Verifies DB connection as well.
 */
export const healthCheckApiV1HealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckApiV1HealthGetData, ThrowOnError>): RequestResult<HealthCheckApiV1HealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthCheckApiV1HealthGetResponses, unknown, ThrowOnError>({ url: '/api/v1/health', ...options });

/**
 * Login
 *
 * Dummy login for Hackathon.
 * Provide any email. If it doesn't exist, it creates a User on the fly.
 * Returns a JWT token.
 */
export const loginApiV1AuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiV1AuthLoginPostData, ThrowOnError>): RequestResult<LoginApiV1AuthLoginPostResponses, LoginApiV1AuthLoginPostErrors, ThrowOnError> => (options.client ?? client).post<LoginApiV1AuthLoginPostResponses, LoginApiV1AuthLoginPostErrors, ThrowOnError>({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get My Profile
 *
 * Return the authenticated user's profile.
 */
export const getMyProfileApiV1UsersMeGet = <ThrowOnError extends boolean = false>(options?: Options<GetMyProfileApiV1UsersMeGetData, ThrowOnError>): RequestResult<GetMyProfileApiV1UsersMeGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetMyProfileApiV1UsersMeGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options
});

/**
 * Update My Profile
 *
 * Update the authenticated user's profile fields.
 */
export const updateMyProfileApiV1UsersMePatch = <ThrowOnError extends boolean = false>(options: Options<UpdateMyProfileApiV1UsersMePatchData, ThrowOnError>): RequestResult<UpdateMyProfileApiV1UsersMePatchResponses, UpdateMyProfileApiV1UsersMePatchErrors, ThrowOnError> => (options.client ?? client).patch<UpdateMyProfileApiV1UsersMePatchResponses, UpdateMyProfileApiV1UsersMePatchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Items
 *
 * List items with pagination. Public endpoint.
 */
export const listItemsApiV1ItemsGet = <ThrowOnError extends boolean = false>(options?: Options<ListItemsApiV1ItemsGetData, ThrowOnError>): RequestResult<ListItemsApiV1ItemsGetResponses, ListItemsApiV1ItemsGetErrors, ThrowOnError> => (options?.client ?? client).get<ListItemsApiV1ItemsGetResponses, ListItemsApiV1ItemsGetErrors, ThrowOnError>({ url: '/api/v1/items/', ...options });

/**
 * Create Item
 *
 * Create a new item. Requires authentication.
 */
export const createItemApiV1ItemsPost = <ThrowOnError extends boolean = false>(options: Options<CreateItemApiV1ItemsPostData, ThrowOnError>): RequestResult<CreateItemApiV1ItemsPostResponses, CreateItemApiV1ItemsPostErrors, ThrowOnError> => (options.client ?? client).post<CreateItemApiV1ItemsPostResponses, CreateItemApiV1ItemsPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/items/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Item
 *
 * Delete an item. Requires authentication.
 */
export const deleteItemApiV1ItemsItemIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteItemApiV1ItemsItemIdDeleteData, ThrowOnError>): RequestResult<DeleteItemApiV1ItemsItemIdDeleteResponses, DeleteItemApiV1ItemsItemIdDeleteErrors, ThrowOnError> => (options.client ?? client).delete<DeleteItemApiV1ItemsItemIdDeleteResponses, DeleteItemApiV1ItemsItemIdDeleteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/items/{item_id}',
    ...options
});

/**
 * Get Item
 *
 * Get a single item by ID.
 */
export const getItemApiV1ItemsItemIdGet = <ThrowOnError extends boolean = false>(options: Options<GetItemApiV1ItemsItemIdGetData, ThrowOnError>): RequestResult<GetItemApiV1ItemsItemIdGetResponses, GetItemApiV1ItemsItemIdGetErrors, ThrowOnError> => (options.client ?? client).get<GetItemApiV1ItemsItemIdGetResponses, GetItemApiV1ItemsItemIdGetErrors, ThrowOnError>({ url: '/api/v1/items/{item_id}', ...options });

/**
 * Update Item
 *
 * Update an item. Requires authentication.
 */
export const updateItemApiV1ItemsItemIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateItemApiV1ItemsItemIdPatchData, ThrowOnError>): RequestResult<UpdateItemApiV1ItemsItemIdPatchResponses, UpdateItemApiV1ItemsItemIdPatchErrors, ThrowOnError> => (options.client ?? client).patch<UpdateItemApiV1ItemsItemIdPatchResponses, UpdateItemApiV1ItemsItemIdPatchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/items/{item_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Traces
 */
export const getTracesApiV1AiTracesGet = <ThrowOnError extends boolean = false>(options?: Options<GetTracesApiV1AiTracesGetData, ThrowOnError>): RequestResult<GetTracesApiV1AiTracesGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetTracesApiV1AiTracesGetResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/ai/traces',
    ...options
});

/**
 * Chat
 */
export const chatApiV1AiChatPost = <ThrowOnError extends boolean = false>(options: Options<ChatApiV1AiChatPostData, ThrowOnError>): RequestResult<ChatApiV1AiChatPostResponses, ChatApiV1AiChatPostErrors, ThrowOnError> => (options.client ?? client).post<ChatApiV1AiChatPostResponses, ChatApiV1AiChatPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/ai/chat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Chat Stream
 */
export const chatStreamApiV1AiChatStreamPost = <ThrowOnError extends boolean = false>(options: Options<ChatStreamApiV1AiChatStreamPostData, ThrowOnError>): RequestResult<ChatStreamApiV1AiChatStreamPostResponses, ChatStreamApiV1AiChatStreamPostErrors, ThrowOnError> => (options.client ?? client).post<ChatStreamApiV1AiChatStreamPostResponses, ChatStreamApiV1AiChatStreamPostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/ai/chat/stream',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Ai Health
 */
export const aiHealthApiV1AiHealthGet = <ThrowOnError extends boolean = false>(options?: Options<AiHealthApiV1AiHealthGetData, ThrowOnError>): RequestResult<AiHealthApiV1AiHealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<AiHealthApiV1AiHealthGetResponses, unknown, ThrowOnError>({ url: '/api/v1/ai/health', ...options });

/**
 * Upload File
 *
 * Upload a file to S3/MinIO.
 * Runs the synchronous boto3 upload in a threadpool to prevent blocking the event loop.
 */
export const uploadFileApiV1UploadPost = <ThrowOnError extends boolean = false>(options: Options<UploadFileApiV1UploadPostData, ThrowOnError>): RequestResult<UploadFileApiV1UploadPostResponses, UploadFileApiV1UploadPostErrors, ThrowOnError> => (options.client ?? client).post<UploadFileApiV1UploadPostResponses, UploadFileApiV1UploadPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/upload/',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Run Background Task
 *
 * Triggers a long-running process in the background.
 * Returns 202 Accepted immediately.
 */
export const runBackgroundTaskApiV1TasksRunPost = <ThrowOnError extends boolean = false>(options?: Options<RunBackgroundTaskApiV1TasksRunPostData, ThrowOnError>): RequestResult<RunBackgroundTaskApiV1TasksRunPostResponses, unknown, ThrowOnError> => (options?.client ?? client).post<RunBackgroundTaskApiV1TasksRunPostResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tasks/run',
    ...options
});
