// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_upload_file_api_v1_upload__post
 */
export type BodyUploadFileApiV1UploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * ChatRequest
 */
export type ChatRequest = {
    /**
     * Message
     */
    message: string;
    /**
     * Session Id
     */
    session_id?: string | null;
    /**
     * Agent Id
     */
    agent_id?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 *
 * Item creation payload.
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Published
     */
    is_published?: boolean;
};

/**
 * ItemRead
 *
 * Item response schema.
 */
export type ItemRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Published
     */
    is_published: boolean;
    /**
     * Owner Id
     */
    owner_id?: string | null;
};

/**
 * ItemUpdate
 *
 * Item update payload — only set fields are applied.
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Published
     */
    is_published?: boolean | null;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * User
     */
    user: {
        [key: string]: unknown;
    };
};

/**
 * StandardResponse
 *
 * Standardize all API responses.
 */
export type StandardResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     */
    data?: unknown | null;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Error Code
     */
    error_code?: string | null;
};

/**
 * StandardResponse[ItemRead]
 */
export type StandardResponseItemRead = {
    /**
     * Success
     */
    success: boolean;
    data?: ItemRead | null;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Error Code
     */
    error_code?: string | null;
};

/**
 * StandardResponse[UserRead]
 */
export type StandardResponseUserRead = {
    /**
     * Success
     */
    success: boolean;
    data?: UserRead | null;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Error Code
     */
    error_code?: string | null;
};

/**
 * StandardResponse[dict]
 */
export type StandardResponseDict = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     */
    data?: {
        [key: string]: unknown;
    } | null;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Error Code
     */
    error_code?: string | null;
};

/**
 * UserRead
 *
 * Full user profile returned by API.
 */
export type UserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Role
     */
    role: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserUpdate
 *
 * Fields that a user can update on their own profile.
 */
export type UserUpdate = {
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type HealthCheckApiV1HealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthCheckApiV1HealthGetResponses = {
    /**
     * Successful Response
     */
    200: StandardResponseDict;
};

export type HealthCheckApiV1HealthGetResponse = HealthCheckApiV1HealthGetResponses[keyof HealthCheckApiV1HealthGetResponses];

export type LoginApiV1AuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type GetMyProfileApiV1UsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetMyProfileApiV1UsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: StandardResponseUserRead;
};

export type GetMyProfileApiV1UsersMeGetResponse = GetMyProfileApiV1UsersMeGetResponses[keyof GetMyProfileApiV1UsersMeGetResponses];

export type UpdateMyProfileApiV1UsersMePatchData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateMyProfileApiV1UsersMePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMyProfileApiV1UsersMePatchError = UpdateMyProfileApiV1UsersMePatchErrors[keyof UpdateMyProfileApiV1UsersMePatchErrors];

export type UpdateMyProfileApiV1UsersMePatchResponses = {
    /**
     * Successful Response
     */
    200: StandardResponseUserRead;
};

export type UpdateMyProfileApiV1UsersMePatchResponse = UpdateMyProfileApiV1UsersMePatchResponses[keyof UpdateMyProfileApiV1UsersMePatchResponses];

export type ListItemsApiV1ItemsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * Page number
         */
        page?: number;
        /**
         * Page Size
         *
         * Items per page
         */
        page_size?: number;
    };
    url: '/api/v1/items/';
};

export type ListItemsApiV1ItemsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListItemsApiV1ItemsGetError = ListItemsApiV1ItemsGetErrors[keyof ListItemsApiV1ItemsGetErrors];

export type ListItemsApiV1ItemsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateItemApiV1ItemsPostData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type CreateItemApiV1ItemsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateItemApiV1ItemsPostError = CreateItemApiV1ItemsPostErrors[keyof CreateItemApiV1ItemsPostErrors];

export type CreateItemApiV1ItemsPostResponses = {
    /**
     * Successful Response
     */
    201: StandardResponseItemRead;
};

export type CreateItemApiV1ItemsPostResponse = CreateItemApiV1ItemsPostResponses[keyof CreateItemApiV1ItemsPostResponses];

export type DeleteItemApiV1ItemsItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/api/v1/items/{item_id}';
};

export type DeleteItemApiV1ItemsItemIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemApiV1ItemsItemIdDeleteError = DeleteItemApiV1ItemsItemIdDeleteErrors[keyof DeleteItemApiV1ItemsItemIdDeleteErrors];

export type DeleteItemApiV1ItemsItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: StandardResponse;
};

export type DeleteItemApiV1ItemsItemIdDeleteResponse = DeleteItemApiV1ItemsItemIdDeleteResponses[keyof DeleteItemApiV1ItemsItemIdDeleteResponses];

export type GetItemApiV1ItemsItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/api/v1/items/{item_id}';
};

export type GetItemApiV1ItemsItemIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemApiV1ItemsItemIdGetError = GetItemApiV1ItemsItemIdGetErrors[keyof GetItemApiV1ItemsItemIdGetErrors];

export type GetItemApiV1ItemsItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: StandardResponseItemRead;
};

export type GetItemApiV1ItemsItemIdGetResponse = GetItemApiV1ItemsItemIdGetResponses[keyof GetItemApiV1ItemsItemIdGetResponses];

export type UpdateItemApiV1ItemsItemIdPatchData = {
    body: ItemUpdate;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/api/v1/items/{item_id}';
};

export type UpdateItemApiV1ItemsItemIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateItemApiV1ItemsItemIdPatchError = UpdateItemApiV1ItemsItemIdPatchErrors[keyof UpdateItemApiV1ItemsItemIdPatchErrors];

export type UpdateItemApiV1ItemsItemIdPatchResponses = {
    /**
     * Successful Response
     */
    200: StandardResponseItemRead;
};

export type UpdateItemApiV1ItemsItemIdPatchResponse = UpdateItemApiV1ItemsItemIdPatchResponses[keyof UpdateItemApiV1ItemsItemIdPatchResponses];

export type GetTracesApiV1AiTracesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ai/traces';
};

export type GetTracesApiV1AiTracesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChatApiV1AiChatPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/chat';
};

export type ChatApiV1AiChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatApiV1AiChatPostError = ChatApiV1AiChatPostErrors[keyof ChatApiV1AiChatPostErrors];

export type ChatApiV1AiChatPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChatStreamApiV1AiChatStreamPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/chat/stream';
};

export type ChatStreamApiV1AiChatStreamPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatStreamApiV1AiChatStreamPostError = ChatStreamApiV1AiChatStreamPostErrors[keyof ChatStreamApiV1AiChatStreamPostErrors];

export type ChatStreamApiV1AiChatStreamPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AiHealthApiV1AiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ai/health';
};

export type AiHealthApiV1AiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadFileApiV1UploadPostData = {
    body: BodyUploadFileApiV1UploadPost;
    path?: never;
    query?: never;
    url: '/api/v1/upload/';
};

export type UploadFileApiV1UploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileApiV1UploadPostError = UploadFileApiV1UploadPostErrors[keyof UploadFileApiV1UploadPostErrors];

export type UploadFileApiV1UploadPostResponses = {
    /**
     * Successful Response
     */
    200: StandardResponse;
};

export type UploadFileApiV1UploadPostResponse = UploadFileApiV1UploadPostResponses[keyof UploadFileApiV1UploadPostResponses];

export type RunBackgroundTaskApiV1TasksRunPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tasks/run';
};

export type RunBackgroundTaskApiV1TasksRunPostResponses = {
    /**
     * Successful Response
     */
    202: StandardResponse;
};

export type RunBackgroundTaskApiV1TasksRunPostResponse = RunBackgroundTaskApiV1TasksRunPostResponses[keyof RunBackgroundTaskApiV1TasksRunPostResponses];
